/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poebase;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import static java.nio.file.StandardCopyOption.REPLACE_EXISTING;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Dano
 */
public class poebase extends javax.swing.JFrame {

    /**
     * Creates new form poebase
     */
    
    static String filePathString=(System.getProperty("user.home") + "\\Desktop\\Poebase\\assets\\database");
    static String filePathString1=(System.getProperty("user.home") + "\\Desktop\\Poebase\\assets\\database\\");
    
    
    public poebase() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cBox1 = new javax.swing.JComboBox<>();
        show_button = new javax.swing.JButton();
        new_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Poebase");

        cBox1.setToolTipText("Choose an item from the box whichever you want ");

        show_button.setText("Show");
        show_button.setToolTipText("Press this button when you want to show detailed information about chosen item");
        show_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_buttonActionPerformed(evt);
            }
        });

        new_button.setText("New");
        new_button.setToolTipText("Press this button, when you want to add a new item");
        new_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_buttonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Item list");

        jMenu1.setText("About");

        jMenuItem1.setText("About");
        jMenuItem1.setToolTipText("Information about this program");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Exit");

        jMenuItem3.setText("Quit");
        jMenuItem3.setToolTipText("Just quit the program bro, obviously");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(show_button)
                    .addComponent(new_button)
                    .addComponent(cBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(show_button)
                .addGap(56, 56, 56)
                .addComponent(new_button)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
   JOptionPane.showMessageDialog(null, "Thanks for using !");
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       new About(this).setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void show_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_buttonActionPerformed
       String chosen_item=(String)cBox1.getSelectedItem();
       File filepath=new File(filePathString +"\\"+chosen_item);
        Showing a=new Showing();
              a.setVisible(true);
              a.setAlwaysOnTop(false);
      try (BufferedReader br = new BufferedReader(new FileReader(filepath+"\\"+chosen_item+".txt"))) {
           a.L1.setIcon(new javax.swing.ImageIcon(filepath+"\\"+chosen_item+".png"));
           Showing.L1.setHorizontalAlignment(JLabel.CENTER);
            String line=null;
                while ((line = br.readLine()) != null) {
                      a.TA1.append(line+"\n");
                 }
        }       catch (Exception e) {
                    JOptionPane.showMessageDialog(this,"This File is corrupted or does not exist","Error",HEIGHT);
                }
        
    }//GEN-LAST:event_show_buttonActionPerformed

    private void new_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_buttonActionPerformed
          JFileChooser chooser=new JFileChooser();
          FileFilter imageFilter = new FileNameExtensionFilter(
    "Image files", ImageIO.getReaderFileSuffixes());
          chooser.setFileFilter(imageFilter);
            JOptionPane.showMessageDialog(chooser,"Pick an Image of your item");
     int r=chooser.showOpenDialog(this);
     if(r==JFileChooser.APPROVE_OPTION){
              try {
                  File f=chooser.getSelectedFile();
                  String g=chooser.getName(f);
                  g=g.replace(".png","");
                  File destinationFolder = new File(filePathString + "\\"+g);
                  File sourceFolder = f;
                  if (!destinationFolder.exists())
                  {
                      destinationFolder.mkdirs();
                  } 
                  
                  Path k=f.toPath();
                  Path l=destinationFolder.toPath();
                Path f1=Files.move(k, l.resolve(l.getFileName()), REPLACE_EXISTING);
                f=f1.toFile();
                File file2=new File(filePathString+"\\"+g+"\\"+g+".png");
                boolean success = f.renameTo(file2);
              } catch (Exception  e) {
                 JOptionPane.showMessageDialog(null,"Error","Error",HEIGHT);
              }
     }
  //------------------------------------------------------------------------   
    FileFilter textFilter = new FileNameExtensionFilter(
    "Text files","txt");
          chooser.setFileFilter(textFilter);
         JOptionPane.showMessageDialog(chooser,"Pick an Text information of your item");
     int h=chooser.showOpenDialog(this);
     if(r==JFileChooser.APPROVE_OPTION){
              try {
                  File f=chooser.getSelectedFile();
                  String g=chooser.getName(f);
                  g=g.replace(".txt","");
                  File destinationFolder = new File(filePathString + "\\"+g);
                  File sourceFolder = f;
                  if (!destinationFolder.exists())
                  {
                      destinationFolder.mkdirs();
                  } 
                  
                   Path k=f.toPath();
                  Path l=destinationFolder.toPath();
                Path f1=Files.move(k, l.resolve(l.getFileName()), REPLACE_EXISTING);
                f=f1.toFile();
                File file2=new File(filePathString+"\\"+g+"\\"+g+".txt");
                boolean success = f.renameTo(file2);
               
              } catch (Exception  e) {
                 JOptionPane.showMessageDialog(null,"Error","Error",HEIGHT);
              } 
     }
       try {
                    cBox1.removeAllItems();
                    Files.walk(Paths.get(filePathString)).forEach(filePath -> {
                        if (Files.isDirectory(filePath)) {
                           String Path=filePath.toString();
                           Path=Path.replace(filePathString1,"");
                           cBox1.addItem(Path);
                           cBox1.removeItem(filePathString);
                        }
                    });             } catch (Exception e) {
                        JOptionPane.showMessageDialog(null,"Chosen path does not exist","Error",HEIGHT);
                   
                }
     
    }//GEN-LAST:event_new_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(poebase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(poebase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(poebase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(poebase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */ 
        java.awt.EventQueue.invokeLater(() -> {
            new poebase().setVisible(true);
            
            try {
                Files.walk(Paths.get(filePathString)).forEach(filePath -> {
                    if (Files.isDirectory(filePath)) {
                        String Path=filePath.toString();
                        Path=Path.replace(filePathString1,"");
                        cBox1.addItem(Path);
                        cBox1.removeItem(filePathString);
                    }
                });             } catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"Chosen path does not exist","Error",HEIGHT);
                    System.exit(0);
                    
                }
        }); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> cBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JButton new_button;
    private javax.swing.JButton show_button;
    // End of variables declaration//GEN-END:variables
}
