;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lineage;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author instal
 */
public class lineage extends javax.swing.JFrame {
   ArrayList<String[]> action = new ArrayList<String[]>();
   String[] pole;
   int age;
   int year;
 int ageMin1=Integer.MAX_VALUE;
  int ageMin2;
  int ageMax1=Integer.MIN_VALUE;
  int ageMax2;
  int average=0;
    public lineage(FileReader fr) {
        initComponents();
       
         try {                
            BufferedReader br=new BufferedReader(fr);
            String savingPoint=null;
            while((savingPoint=br.readLine()) !=null){          
            pole =savingPoint.split(",");
            //System.out.println(Arrays.toString(pole));
            action.add(pole);
            }
            
            
             jButton1.setText(action.get(0)[0]);
            jButton2.setText(action.get(1)[0]);
             jButton3.setText(action.get(2)[0]);
              jButton4.setText(action.get(3)[0]);
               jButton5.setText(action.get(4)[0]);
                jButton6.setText(action.get(5)[0]);
                 jButton7.setText(action.get(6)[0]);
                  jButton8.setText(action.get(7)[0]);
                   jButton9.setText(action.get(8)[0]);
                    jButton10.setText(action.get(9)[0]);
                     jButton11.setText(action.get(10)[0]);
                      jButton12.setText(action.get(11)[0]);
                       jButton13.setText(action.get(12)[0]);
                        jButton14.setText(action.get(13)[0]);
                         jButton15.setText(action.get(14)[0]);
                         
                         
                          if(action.size() <=  15){
                                jButton18.setVisible(false);
                                jButton19.setVisible(false);
                                System.out.println(action.size());
        }
                          if(action.size() >  15){
                                jButton18.setVisible(true);
                                jButton19.setVisible(true);
                                jButton18.setText(action.get(15)[0]);
                                jButton19.setText(action.get(16)[0]);
                          }         
            }   catch (FileNotFoundException ex) {
                    Logger.getLogger(lineage.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(lineage.class.getName()).log(Level.SEVERE, null, ex);
                }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();

        setTitle("Lineage");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Calibri", 0, 10)); // NOI18N
        setResizable(false);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("jButton6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("jButton7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("jButton8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("jButton9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("jButton10");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("jButton11");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("jButton12");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("jButton13");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("jButton14");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("jButton15");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton17.setText("Dĺžka života");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton16.setText("Close");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton18.setText("jButton18");
        jButton18.setOpaque(false);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton19.setText("jButton19");
        jButton19.setOpaque(false);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButton20.setText("Pridať generáciu");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jLabel1.setText("Mamina Strana");

        jLabel2.setText("Otcova Strana");

        jButton21.setText("Reload");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(255, 255, 255))
            .addGroup(layout.createSequentialGroup()
                .addGap(704, 704, 704)
                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(270, 270, 270))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(686, 686, 686))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(230, 230, 230)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(838, 838, 838)
                        .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(425, 425, 425)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6)
                            .addComponent(jButton5)
                            .addComponent(jButton4)
                            .addComponent(jButton3)
                            .addComponent(jButton2)
                            .addComponent(jButton1)
                            .addComponent(jButton8)
                            .addComponent(jButton7))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton10)
                                    .addComponent(jButton9)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton12)
                                    .addComponent(jButton11)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))))
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton14)
                    .addComponent(jButton13))
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton15)
                    .addComponent(jButton18))
                .addGap(55, 55, 55)
                .addComponent(jButton19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
   new info().setVisible(true);
         info.jTextField1.setText(action.get(11)[0]);
         if((action.get(11)[3]).equals(String.valueOf(0))){
           int year = Calendar.getInstance().get(Calendar.YEAR);   
           age=(year - (Integer.parseInt(action.get(11)[2])));
           info.jTextField2.setText(String.valueOf(age));
         }
        else {
         age=Integer.parseInt(action.get(11)[3]) - Integer.parseInt(action.get(11)[2]);
         info.jTextField2.setText(String.valueOf(age));
        }       
         info.jTextField3.setText(action.get(11)[2]);
         if(Integer.parseInt(action.get(11)[3])==0)
         info.jTextField4.setText("ešte žije");
         else info.jTextField4.setText(action.get(11)[3]);
         info.jTextField5.setText(action.get(11)[4]);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         new info().setVisible(true);
         info.jTextField1.setText(action.get(0)[0]);
         if((action.get(0)[3]).equals(String.valueOf(0))){
           int year = Calendar.getInstance().get(Calendar.YEAR);   
           age=(year - (Integer.parseInt(action.get(0)[2])));
           info.jTextField2.setText(String.valueOf(age));
         }
        else {
         age=Integer.parseInt(action.get(0)[3]) - Integer.parseInt(action.get(0)[2]);
         info.jTextField2.setText(String.valueOf(age));
        }       
         info.jTextField3.setText(action.get(0)[2]);
         if(Integer.parseInt(action.get(0)[3])==0)
         info.jTextField4.setText("ešte žije");
         else
         info.jTextField4.setText(action.get(0)[3]); 
         info.jTextField5.setText(action.get(0)[4]);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       new info().setVisible(true);
         info.jTextField1.setText(action.get(1)[0]);
         if((action.get(1)[3]).equals(String.valueOf(0))){
           int year = Calendar.getInstance().get(Calendar.YEAR);     
           age=(year - (Integer.parseInt(action.get(1)[2])));
           info.jTextField2.setText(String.valueOf(age));
         }
        else {
         age=Integer.parseInt(action.get(1)[3]) - Integer.parseInt(action.get(1)[2]);
         info.jTextField2.setText(String.valueOf(age));
        }       
         info.jTextField3.setText(action.get(1)[2]);
         if(Integer.parseInt(action.get(1)[3])==0)
         info.jTextField4.setText("ešte žije");
         else
         info.jTextField4.setText(action.get(1)[3]); 
         info.jTextField5.setText(action.get(1)[4]);       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      new info().setVisible(true);
         info.jTextField1.setText(action.get(2)[0]);
         if((action.get(2)[3]).equals(String.valueOf(0))){
           int year = Calendar.getInstance().get(Calendar.YEAR);         
           age=(year - (Integer.parseInt(action.get(2)[2])));
           info.jTextField2.setText(String.valueOf(age));
         }
        else {
         age=Integer.parseInt(action.get(2)[3]) - Integer.parseInt(action.get(2)[2]);
         info.jTextField2.setText(String.valueOf(age));
        }       
         info.jTextField3.setText(action.get(2)[2]);
         if(Integer.parseInt(action.get(2)[3])==0)
         info.jTextField4.setText("ešte žije");
         else
         info.jTextField4.setText(action.get(2)[3]); 
         info.jTextField5.setText(action.get(2)[4]);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
   new info().setVisible(true);
         info.jTextField1.setText(action.get(3)[0]);
         if((action.get(3)[3]).equals(String.valueOf(0))){
           int year = Calendar.getInstance().get(Calendar.YEAR);   
           age=(year - (Integer.parseInt(action.get(3)[2])));
           info.jTextField2.setText(String.valueOf(age));
         }
        else {
         age=Integer.parseInt(action.get(3)[3]) - Integer.parseInt(action.get(3)[2]);
         info.jTextField2.setText(String.valueOf(age));
        }       
         info.jTextField3.setText(action.get(3)[2]);
         if(Integer.parseInt(action.get(3)[3])==0)
         info.jTextField4.setText("ešte žije");
         else
         info.jTextField4.setText(action.get(3)[3]); 
         info.jTextField5.setText(action.get(3)[4]);    
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       new info().setVisible(true);
         info.jTextField1.setText(action.get(4)[0]);
         if((action.get(4)[3]).equals(String.valueOf(0))){
           int year = Calendar.getInstance().get(Calendar.YEAR);   
           age=(year - (Integer.parseInt(action.get(0)[2])));
           info.jTextField2.setText(String.valueOf(age));
         }
        else {
         age=Integer.parseInt(action.get(4)[3]) - Integer.parseInt(action.get(4)[2]);
         info.jTextField2.setText(String.valueOf(age));
        }       
         info.jTextField3.setText(action.get(4)[2]);
         if(Integer.parseInt(action.get(4)[3])==0)
         info.jTextField4.setText("ešte žije");
         else
         info.jTextField4.setText(action.get(4)[3]); 
         info.jTextField5.setText(action.get(4)[4]);        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
      new info().setVisible(true);
         info.jTextField1.setText(action.get(5)[0]);
         if((action.get(5)[3]).equals(String.valueOf(0))){
           int year = Calendar.getInstance().get(Calendar.YEAR);   
           age=(year - (Integer.parseInt(action.get(0)[2])));
           info.jTextField2.setText(String.valueOf(age));
         }
        else {
         age=Integer.parseInt(action.get(5)[3]) - Integer.parseInt(action.get(5)[2]);
         info.jTextField2.setText(String.valueOf(age));
        }       
         info.jTextField3.setText(action.get(5)[2]);
         if(Integer.parseInt(action.get(5)[3])==0)
         info.jTextField4.setText("ešte žije");
         else
         info.jTextField4.setText(action.get(5)[3]); 
         info.jTextField5.setText(action.get(5)[4]);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
   new info().setVisible(true);
         info.jTextField1.setText(action.get(6)[0]);
         if((action.get(6)[3]).equals(String.valueOf(0))){
           int year = Calendar.getInstance().get(Calendar.YEAR);   
           age=(year - (Integer.parseInt(action.get(6)[2])));
           info.jTextField2.setText(String.valueOf(age));
         }
        else {
         age=Integer.parseInt(action.get(6)[3]) - Integer.parseInt(action.get(6)[2]);
         info.jTextField2.setText(String.valueOf(age));
        }       
         info.jTextField3.setText(action.get(6)[2]);
         if(Integer.parseInt(action.get(6)[3])==0)
         info.jTextField4.setText("ešte žije");
         else
         info.jTextField4.setText(action.get(6)[3]); 
         info.jTextField5.setText(action.get(6)[4]);       
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
   new info().setVisible(true);
         info.jTextField1.setText(action.get(7)[0]);
         if((action.get(7)[3]).equals(String.valueOf(0))){
           int year = Calendar.getInstance().get(Calendar.YEAR);   
           age=(year - (Integer.parseInt(action.get(7)[2])));
           info.jTextField2.setText(String.valueOf(age));
         }
        else {
         age=Integer.parseInt(action.get(7)[3]) - Integer.parseInt(action.get(7)[2]);
         info.jTextField2.setText(String.valueOf(age));
        }       
         info.jTextField3.setText(action.get(7)[2]);
         if(Integer.parseInt(action.get(7)[3])==0)
         info.jTextField4.setText("ešte žije");
         else
         info.jTextField4.setText(action.get(7)[3]); 
         info.jTextField5.setText(action.get(7)[4]);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        new info().setVisible(true);
        info.jTextField1.setText(action.get(8)[0]);
        if((action.get(8)[3]).equals(String.valueOf(0))){
           int year = Calendar.getInstance().get(Calendar.YEAR);   
           age=(year - (Integer.parseInt(action.get(8)[2])));
           info.jTextField2.setText(String.valueOf(age));
        }
        else {
            age=Integer.parseInt(action.get(8)[3]) - Integer.parseInt(action.get(8)[2]);
            info.jTextField2.setText(String.valueOf(age));
        }       
        info.jTextField3.setText(action.get(8)[2]);
        if(Integer.parseInt(action.get(8)[3])==0)
            info.jTextField4.setText("ešte žije");
        else
            info.jTextField4.setText(action.get(8)[3]); 
        info.jTextField5.setText(action.get(8)[4]);      
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
   new info().setVisible(true);
         info.jTextField1.setText(action.get(9)[0]);
         if((action.get(9)[3]).equals(String.valueOf(0))){
           int year = Calendar.getInstance().get(Calendar.YEAR);   
           age=(year - (Integer.parseInt(action.get(9)[2])));
           info.jTextField2.setText(String.valueOf(age));
         }
        else {
         age=Integer.parseInt(action.get(9)[3]) - Integer.parseInt(action.get(9)[2]);
         info.jTextField2.setText(String.valueOf(age));
        }       
         info.jTextField3.setText(action.get(9)[2]);
         if(Integer.parseInt(action.get(9)[3])==0)
         info.jTextField4.setText("ešte žije");
         else
         info.jTextField4.setText(action.get(9)[3]); 
         info.jTextField5.setText(action.get(9)[4]);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
   new info().setVisible(true);
         info.jTextField1.setText(action.get(10)[0]);
         if((action.get(10)[3]).equals(String.valueOf(0))){
           int year = Calendar.getInstance().get(Calendar.YEAR);   
           age=(year - (Integer.parseInt(action.get(10)[2])));
           info.jTextField2.setText(String.valueOf(age));
         }
        else {
         age=Integer.parseInt(action.get(10)[3]) - Integer.parseInt(action.get(10)[2]);
         info.jTextField2.setText(String.valueOf(age));
        }       
         info.jTextField3.setText(action.get(10)[2]);
         if(Integer.parseInt(action.get(10)[3])==0)
         info.jTextField4.setText("ešte žije");
         else
         info.jTextField4.setText(action.get(10)[3]); 
         info.jTextField5.setText(action.get(10)[4]);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
   new info().setVisible(true);
         info.jTextField1.setText(action.get(12)[0]);
         if((action.get(12)[3]).equals(String.valueOf(0))){
           int year = Calendar.getInstance().get(Calendar.YEAR);   
           age=(year - (Integer.parseInt(action.get(12)[2])));
           info.jTextField2.setText(String.valueOf(age));
         }
        else {
         age=Integer.parseInt(action.get(12)[3]) - Integer.parseInt(action.get(12)[2]);
         info.jTextField2.setText(String.valueOf(age));
        }       
         info.jTextField3.setText(action.get(12)[2]);
         if(Integer.parseInt(action.get(12)[3])==0)
         info.jTextField4.setText("ešte žije");
         else
         info.jTextField4.setText(action.get(12)[3]); 
         info.jTextField5.setText(action.get(12)[4]);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
   new info().setVisible(true);
         info.jTextField1.setText(action.get(13)[0]);
         if((action.get(13)[3]).equals(String.valueOf(0))){
           int year = Calendar.getInstance().get(Calendar.YEAR);   
           age=(year - (Integer.parseInt(action.get(13)[2])));
           info.jTextField2.setText(String.valueOf(age));
         }
        else {
         age=Integer.parseInt(action.get(13)[3]) - Integer.parseInt(action.get(13)[2]);
         info.jTextField2.setText(String.valueOf(age));
        }       
         info.jTextField3.setText(action.get(13)[2]);
         if(Integer.parseInt(action.get(13)[3])==0)
         info.jTextField4.setText("ešte žije");
         else
         info.jTextField4.setText(action.get(13)[3]); 
         info.jTextField5.setText(action.get(13)[4]);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
   new info().setVisible(true);
         info.jTextField1.setText(action.get(14)[0]);
         if((action.get(14)[3]).equals(String.valueOf(0))){
           int year = Calendar.getInstance().get(Calendar.YEAR);   
           age=(year - (Integer.parseInt(action.get(14)[2])));
           info.jTextField2.setText(String.valueOf(age));
         }
        else {
         age=Integer.parseInt(action.get(14)[3]) - Integer.parseInt(action.get(14)[2]);
         info.jTextField2.setText(String.valueOf(age));
        }       
         info.jTextField3.setText(action.get(14)[2]);
         if(Integer.parseInt(action.get(14)[3])==0)
         info.jTextField4.setText("ešte žije");
         else
         info.jTextField4.setText(action.get(14)[3]); 
         info.jTextField5.setText(action.get(14)[4]);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        new life().setVisible(true);

        for(int i=0;i<action.size();i++){
            if((action.get(i)[3]).equals(String.valueOf(0))){
                year=Calendar.getInstance().get(Calendar.YEAR);
                ageMax2=(year -(Integer.parseInt(action.get(i)[2])));
                ageMax1=Math.max(ageMax2, ageMax1);
            }
            else {
                ageMax2=Integer.parseInt(action.get(i)[3]) - Integer.parseInt(action.get(i)[2]);}
            ageMax1=Math.max(ageMax2, ageMax1);
            average=ageMax2+average;
        }

        for(int i=0;i<action.size();i++){
            if((Integer.parseInt(action.get(i)[3])) !=0){
                ageMin2= (Integer.parseInt(action.get(i)[3]) - Integer.parseInt(action.get(i)[2]));
                ageMin1= Math.min(ageMin2, ageMin1);
            }
        }

        for(int i=0;i<action.size();i++){
            if((Integer.parseInt(action.get(i)[3])- Integer.parseInt(action.get(i)[2]))==ageMax1){
                String longest=action.get(i)[0];
                life.jTextField1.setText(longest);
                life.jTextField3.setText(String.valueOf(ageMax1) + " rokov");
            }
        }

        for(int i=0;i<action.size();i++){
            if((Integer.parseInt(action.get(i)[3]) !=0)  & (Integer.parseInt(action.get(i)[3])- Integer.parseInt(action.get(i)[2]))==ageMin1){
                String shortest=action.get(i)[0];
                life.jTextField2.setText(shortest);
                life.jTextField4.setText(String.valueOf(ageMin1) + " rokov");
            }
        }

        int averageFinal= (average / action.size());
        life.jTextField5.setText(String.valueOf(averageFinal) + " rokov");

    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
     new generation().setVisible(true);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
      new info().setVisible(true);
         info.jTextField1.setText(action.get(15)[0]);
         if((action.get(15)[3]).equals(String.valueOf(0))){
           int year = Calendar.getInstance().get(Calendar.YEAR);   
           age=(year - (Integer.parseInt(action.get(15)[2])));
           info.jTextField2.setText(String.valueOf(age));
         }
        else {
         age=Integer.parseInt(action.get(15)[3]) - Integer.parseInt(action.get(15)[2]);
         info.jTextField2.setText(String.valueOf(age));
        }       
         info.jTextField3.setText(action.get(15)[2]);
         if(Integer.parseInt(action.get(15)[3])==0)
         info.jTextField4.setText("ešte žije");
         else
         info.jTextField4.setText(action.get(15)[3]); 
         info.jTextField5.setText(action.get(15)[4]); 
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
 new info().setVisible(true);
         info.jTextField1.setText(action.get(16)[0]);
         if((action.get(16)[3]).equals(String.valueOf(0))){
           int year = Calendar.getInstance().get(Calendar.YEAR);   
           age=(year - (Integer.parseInt(action.get(14)[2])));
           info.jTextField2.setText(String.valueOf(age));
         }
        else {
         age=Integer.parseInt(action.get(16)[3]) - Integer.parseInt(action.get(16)[2]);
         info.jTextField2.setText(String.valueOf(age));
        }       
         info.jTextField3.setText(action.get(16)[2]);
         if(Integer.parseInt(action.get(16)[3])==0)
         info.jTextField4.setText("ešte žije");
         else
         info.jTextField4.setText(action.get(16)[3]); 
         info.jTextField5.setText(action.get(16)[4]);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        action.clear();
         try {    
             FileReader fr=new FileReader(System.getProperty("user.home")+Gui.filepath);
            BufferedReader br=new BufferedReader(fr);
            String savingPoint=null;
            while((savingPoint=br.readLine()) !=null){          
            pole =savingPoint.split(",");
            //System.out.println(Arrays.toString(pole));
            action.add(pole);
            
           }
         } catch (IOException ex) {
           Logger.getLogger(lineage.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        jButton1.setText(action.get(0)[0]);
        jButton2.setText(action.get(1)[0]);
        jButton3.setText(action.get(2)[0]);
        jButton4.setText(action.get(3)[0]);
        jButton5.setText(action.get(4)[0]);
        jButton6.setText(action.get(5)[0]);
        jButton7.setText(action.get(6)[0]);
        jButton8.setText(action.get(7)[0]);
        jButton9.setText(action.get(8)[0]);
        jButton10.setText(action.get(9)[0]);
        jButton11.setText(action.get(10)[0]);
        jButton12.setText(action.get(11)[0]);
        jButton13.setText(action.get(12)[0]);
        jButton14.setText(action.get(13)[0]);
        jButton15.setText(action.get(14)[0]);
        if(action.size() > 15){
            jButton18.setText(action.get(15)[0]);
            jButton19.setText(action.get(16)[0]);
            jButton18.setVisible(true);
            jButton19.setVisible(true);
        }
        
    }//GEN-LAST:event_jButton21ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lineage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lineage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lineage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lineage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new lineage().setResizable(false); 
            }     
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton jButton1;
    private static javax.swing.JButton jButton10;
    private static javax.swing.JButton jButton11;
    private static javax.swing.JButton jButton12;
    private static javax.swing.JButton jButton13;
    private static javax.swing.JButton jButton14;
    private static javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private static javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private static javax.swing.JButton jButton3;
    private static javax.swing.JButton jButton4;
    private static javax.swing.JButton jButton5;
    private static javax.swing.JButton jButton6;
    private static javax.swing.JButton jButton7;
    private static javax.swing.JButton jButton8;
    private static javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
